### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by nurgel** [inteoryx/get-tweets#1]
python get_tweets.py POTUS

AssertionError: Failed request to https://twitter.com/i/api/graphql/dKysYIpQULFHQ5In5aGW-w/UserTweetsAndReplies.  400.  Please submit an issue including this information.

Am i doing something wrong?

**Comment by inteoryx** [comment]
This fell out of date due to changes on Twitter's end.  Just pushed a fix for this, it should work now if you pull the latest and try again.  If other people start to use this project I will update it to automatically account for problems like this.  If that doesn't happen I will just manually react whenever there is an issue.

Thanks for raising this!  Let me know if it doesn't work for you.  (You'll need to invoke the script like this: python get_tweets.py --username POTUS)

**Comment by nurgel** [comment]
Thanks for looking into it.
